baseurl: "https://stltech.org"
title: "STL Tech"
theme: "dimension"
languageCode: "en-us"
defaultContentLanguage: "en"
enableRobotsTXT: true

disableKinds:
  - RSS

params:
  logo: "fa-rocket"
  copyright: "the STL Tech Administrators"

languages:
  en:
    languageName: English
    weight: 1
    title: "STL Tech"
    description: |
      The Online Home of the St. Louis Tech Community. <br />
      <div id="CommunityInviter"></div>
      <script>
      window.CommunityInviterAsyncInit = function () {
      CommunityInviter.init({
      app_url:'default',
      team_id:'stl-tech'
      })
      };
      (function(d, s, id){
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement(s); js.id = id;
      js.src = "https://communityinviter.com/js/communityinviter.js";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'Community_Inviter'));
      </script>
