baseurl: "https://stltech.org"
title: "STL Tech"
theme: "dimension"
languageCode: "en-us"
defaultContentLanguage: "en"
enableRobotsTXT: true

disableKinds:
  - RSS

params:
  logo: "fa-rocket"
  copyright: "the STL Tech Administrators"

languages:
  en:
    languageName: English
    weight: 1
    title: "STL Tech"
    description: |
      The Online Home of the St. Louis Tech Community. <br />
      <a href="http://slack.stltech.org">Join us on Slack</a>; We want to get to know you! <br />
      <a href="http://slack.stltech.org"><img src="http://slack.stltech.org/badge.svg" alt="Slack Status" /></a>
